package sk.upjs.invoicesystem.forms;

import java.awt.Color;
import org.bson.types.ObjectId;
import sk.upjs.invoicesystem.CompaniesDao;
import sk.upjs.invoicesystem.ObjectFactory;
import sk.upjs.invoicesystem.Company;

/**
 *
 * @author kriza
 */
public class CreateCompanyForm extends javax.swing.JDialog {

    private CreateInvoiceForm createInvoiceForm;
    private CompaniesDao companies = ObjectFactory.INSTANCE.getCompanyDao();
    private Company selected = null;
    private String whoIsCreating = null;

    /**
     * Creates new form CreateInvoiceForm
     */
    public CreateCompanyForm(javax.swing.JDialog parent, boolean modal, int selectedRow) {
        super(parent, modal);
        initComponents();

        selected = companies.getCompanies().get(selectedRow);

        companyNameField.setText(selected.getCompanyName());
        streetField.setText(selected.getStreet());
        cityField.setText(selected.getCity());
        if (selected.getPostalCode() != null) {
            ZIPField.setText(Integer.toString(selected.getPostalCode()));
        }
        countryField.setText(selected.getCountry());
        if (selected.getICO() != null) {
            ICOField.setText(Long.toString(selected.getICO()));
        }
        if (selected.getDIC() != null) {
            DICField.setText(Long.toString(selected.getDIC()));
        }
        if (selected.getICDPH() != null) {
            DPHField.setText(Long.toString(selected.getICDPH()));
        }
        telephoneNumberField.setText(selected.getTelephoneNumber());
        emailField.setText(selected.getEmail());
        IBANField.setText(selected.getIBAN());
        createCompanyButton.setText("Update");
    }

    public CreateCompanyForm(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    public CreateCompanyForm(javax.swing.JDialog parent, boolean modal, String whoIsCreating) {
        super(parent, modal);
        initComponents();
        this.whoIsCreating = whoIsCreating;
        createInvoiceForm = (CreateInvoiceForm) parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        companyNameField = new javax.swing.JTextField();
        ZIPField = new javax.swing.JTextField();
        streetField = new javax.swing.JTextField();
        cityField = new javax.swing.JTextField();
        countryField = new javax.swing.JTextField();
        DPHField = new javax.swing.JTextField();
        DICField = new javax.swing.JTextField();
        ICOField = new javax.swing.JTextField();
        IBANField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        telephoneNumberField = new javax.swing.JTextField();
        createCompanyButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create company");

        companyNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                companyNameFieldFocusLost(evt);
            }
        });
        companyNameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                companyNameFieldMouseExited(evt);
            }
        });
        companyNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyNameFieldActionPerformed(evt);
            }
        });

        ZIPField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ZIPFieldFocusLost(evt);
            }
        });

        streetField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                streetFieldFocusLost(evt);
            }
        });

        cityField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cityFieldFocusLost(evt);
            }
        });

        countryField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                countryFieldFocusLost(evt);
            }
        });

        DPHField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                DPHFieldFocusLost(evt);
            }
        });

        DICField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                DICFieldFocusLost(evt);
            }
        });

        ICOField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ICOFieldFocusLost(evt);
            }
        });

        IBANField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                IBANFieldFocusLost(evt);
            }
        });

        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });

        telephoneNumberField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                telephoneNumberFieldFocusLost(evt);
            }
        });

        createCompanyButton.setText("Create!");
        createCompanyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCompanyButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Company name");

        jLabel16.setText("Street");

        jLabel17.setText("City");

        jLabel18.setText("ZIP");

        jLabel19.setText("Country");

        jLabel20.setText("ICO");

        jLabel21.setText("DIC");

        jLabel22.setText("ICDPH");

        jLabel23.setText("Telephone number");

        jLabel24.setText("Email");

        jLabel25.setText("IBAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(createCompanyButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel5))
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(companyNameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(DICField)
                            .addComponent(DPHField)
                            .addComponent(telephoneNumberField)
                            .addComponent(emailField)
                            .addComponent(IBANField)
                            .addComponent(ZIPField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(countryField)
                            .addComponent(ICOField)
                            .addComponent(cityField)
                            .addComponent(streetField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companyNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(streetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZIPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ICOField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DICField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DPHField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telephoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IBANField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(createCompanyButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createCompanyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCompanyButtonActionPerformed

        if (companyNameField.getText().isEmpty() || streetField.getText().isEmpty()
                || cityField.getText().isEmpty() || ZIPField.getText().isEmpty()
                || countryField.getText().isEmpty()) {
            new BadFilledForm(this, true, "First five fields can not be empty!").setVisible(true);
        } else {
            try {
                Company newOne = new Company();

                newOne.setCompanyName(companyNameField.getText());
                newOne.setStreet(streetField.getText());
                newOne.setCity(cityField.getText());

                if (!ZIPField.getText().isEmpty()) {
                    newOne.setPostalCode(Integer.parseInt(ZIPField.getText()));
                }
                newOne.setCountry(countryField.getText());
                if (!ICOField.getText().isEmpty()) {
                    newOne.setICO(Long.parseLong(ICOField.getText()));
                }
                if (!DICField.getText().isEmpty()) {
                    newOne.setDIC(Long.parseLong(DICField.getText()));
                }
                if (!DPHField.getText().isEmpty()) {
                    newOne.setICDPH(Long.parseLong(DPHField.getText()));
                }
                newOne.setTelephoneNumber(telephoneNumberField.getText());
                newOne.setEmail(emailField.getText());
                newOne.setIBAN(IBANField.getText());

                if (whoIsCreating != null) {

                    if ("supplier".equals(whoIsCreating)) {
                        createInvoiceForm.setSupplier(newOne);
                        createInvoiceForm.setButtonTextChooseSupplier(newOne.getCompanyName());
                        companies.addCompany(newOne);

                    }
                    if ("customer".equals(whoIsCreating)) {
                        createInvoiceForm.setCustomer(newOne);
                        createInvoiceForm.setButtonTextChooseCustomer(newOne.getCompanyName());
                        companies.addCompany(newOne);

                    }
                } else {

                    if (selected != null) {
                        newOne.setIdCompany(selected.getIdCompany());

                        companies.updateCompany(newOne);

                    } else {
                        companies.addCompany(newOne);
                    }
                }
                this.dispose();
            } catch (NumberFormatException e) {
                new BadFilledForm(this, true, "Repair all red fields").setVisible(true);

            }

        }
    }//GEN-LAST:event_createCompanyButtonActionPerformed

    private void companyNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyNameFieldActionPerformed

    private void companyNameFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companyNameFieldMouseExited

    }//GEN-LAST:event_companyNameFieldMouseExited

    private void companyNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_companyNameFieldFocusLost

     }//GEN-LAST:event_companyNameFieldFocusLost

    private void streetFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_streetFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_streetFieldFocusLost

    private void cityFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cityFieldFocusLost

    private void ZIPFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ZIPFieldFocusLost
        try {
            ZIPField.setForeground(Color.black);

            if (!ZIPField.getText().isEmpty()) {
                Integer.parseInt(ZIPField.getText());
            }
        } catch (NumberFormatException e) {
            ZIPField.setForeground(Color.red);
            new BadFilledForm(this, true, "ZIP must be a number!").setVisible(true);
        }
    }//GEN-LAST:event_ZIPFieldFocusLost

    private void countryFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_countryFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_countryFieldFocusLost

    private void ICOFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ICOFieldFocusLost
        try {
            ICOField.setForeground(Color.black);
            if (!ICOField.getText().isEmpty()) {
                Long.parseLong(ICOField.getText());
            }
        } catch (NumberFormatException e) {
            ICOField.setForeground(Color.red);
            new BadFilledForm(this, true, "ICO must be a number!").setVisible(true);
        }    }//GEN-LAST:event_ICOFieldFocusLost

    private void DICFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DICFieldFocusLost
        try {
            DICField.setForeground(Color.black);

            if (!DICField.getText().isEmpty()) {
                Long.parseLong(DICField.getText());
            }
        } catch (NumberFormatException e) {
            DICField.setForeground(Color.red);
            new BadFilledForm(this, true, "DIC must be a number!").setVisible(true);

        }    }//GEN-LAST:event_DICFieldFocusLost

    private void DPHFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DPHFieldFocusLost
        try {
            DPHField.setForeground(Color.black);

            if (!DPHField.getText().isEmpty()) {
                Long.parseLong(DPHField.getText());
            }
        } catch (NumberFormatException e) {
            DPHField.setForeground(Color.red);
            new BadFilledForm(this, true, "ICDPH must be a number!").setVisible(true);
        }    }//GEN-LAST:event_DPHFieldFocusLost

    private void telephoneNumberFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telephoneNumberFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneNumberFieldFocusLost

    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldFocusLost

    private void IBANFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IBANFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_IBANFieldFocusLost

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DICField;
    private javax.swing.JTextField DPHField;
    private javax.swing.JTextField IBANField;
    private javax.swing.JTextField ICOField;
    private javax.swing.JTextField ZIPField;
    private javax.swing.JTextField cityField;
    private javax.swing.JTextField companyNameField;
    private javax.swing.JTextField countryField;
    private javax.swing.JButton createCompanyButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField streetField;
    private javax.swing.JTextField telephoneNumberField;
    // End of variables declaration//GEN-END:variables
}
